Develop
sdtsnake/algoritmia pull request #2
Opened 2023-02-13 02:32 UTC by sdtsnake

Se terminan los ejercicios se arregla el problema para hacer los PR y se hacen los ajustes que cesar anota mediante wattsap ya que no funcionaba el de separación de arreglos porque el elemento igual se estaba teniendo en cuenta para el arreglo equivocado.

2023-02-13 13:23 UTC, ksrarc requested changes
La carpeta ./build no debe estar en git, eliminar

2023-02-13 13:32 UTC, ksrarc requested changes
Para aprender algo nuevo, como hay mucho codigo de pruebas, esto se puede mejorar/simplificar un poco. ver https://www.baeldung.com/parameterized-tests-junit-5

aplicarlo a todas las pruebas

2023-02-13 13:32 UTC, ksrarc commented on src/main/java/clase1/Arreglos.java
> +            if(Numeros.min(elemento, numero) < numero){
Mucho codigo, simplificar

2023-02-13 13:32 UTC, ksrarc commented on src/main/resources/src/main/java/work/oscarramos/clase1/Arreglos.java
> +}
Esta duplicado, no debe existir un src dentro del src, eliminar

2023-02-13 13:32 UTC, ksrarc commented on src/test/java/clase1/ArreglosTest.java
> +class ArreglosTest {
Que pasa con casos super extremos? arreglos nulos? no hay pruebas

2023-02-13 21:29 UTC, sdtsnake commented on src/main/resources/src/main/java/work/oscarramos/clase1/Arreglos.java
> +}
eliminado

2023-02-13 21:30 UTC, sdtsnake commented
> La carpeta ./build no debe estar en git, eliminar

2023-02-14 21:51 UTC, sdtsnake commented
> Para aprender algo nuevo, como hay mucho codigo de pruebas, esto se puede mejorar/simplificar un poco. ver https://www.baeldung.com/parameterized-tests-junit-5
> 
> aplicarlo a todas las pruebas

se mejora las pruebas unitarias según el articulo.

2023-02-14 22:11 UTC, ksrarc requested changes

2023-02-14 22:11 UTC, ksrarc commented on src/main/java/work/oscarramos/clase1/Arreglos.java
> +            if(Numeros.min(elemento, numero) < numero){
Se puede simplificar

2023-02-15 01:48 UTC, sdtsnake commented on src/main/java/work/oscarramos/clase1/Arreglos.java
> +            if(Numeros.min(elemento, numero) < numero){
se realiza ajustes solicitados

2023-02-15 01:49 UTC, sdtsnake commented on src/test/java/clase1/ArreglosTest.java
> +class ArreglosTest {
se incluye validacion de arreglos nulos

2023-02-15 04:11 UTC, ksrarc requested changes

2023-02-15 04:11 UTC, ksrarc commented on src/main/java/work/oscarramos/clase1/Arreglos.java
> +            int res = (Numeros.min(elemento, numero) < numero) ? (arregloMenores[idxMenor++] = elemento):(arregloMayores[idxMayor++] = elemento);
Esto solo lo complica, por qué se hace uso de la función min cuando no es necesaria?

2023-02-15 13:55 UTC, sdtsnake commented on src/main/java/work/oscarramos/clase1/Arreglos.java
> +            if(Numeros.min(elemento, numero) < numero){
se realiza otro ajuste.

2023-02-15 13:56 UTC, sdtsnake commented on src/main/java/work/oscarramos/clase1/Arreglos.java
> +            int res = (Numeros.min(elemento, numero) < numero) ? (arregloMenores[idxMenor++] = elemento):(arregloMayores[idxMayor++] = elemento);
se cambia el codigo.

2023-02-15 15:43 UTC, sdtsnake commented on src/main/java/work/oscarramos/clase1/Arreglos.java
> +            if(Numeros.min(elemento, numero) < numero){
otro ajuste con guía de Victor

2023-02-15 18:55 UTC, ksrarc approved these changes

2023-02-15 21:23 UTC, merged